# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_streaming.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15video_streaming.proto\"\x1b\n\nVideoFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\" \n\rVideoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2G\n\x15VideoStreamingService\x12.\n\x0bStreamVideo\x12\x0b.VideoFrame\x1a\x0e.VideoResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAME']._serialized_start=25
  _globals['_VIDEOFRAME']._serialized_end=52
  _globals['_VIDEORESPONSE']._serialized_start=54
  _globals['_VIDEORESPONSE']._serialized_end=86
  _globals['_VIDEOSTREAMINGSERVICE']._serialized_start=88
  _globals['_VIDEOSTREAMINGSERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
